### ISSUE TITLE
Fatal error: Class 'MageDebugBar\MageDebugBar' not found

### ISSUE THREAD

**Issue by coresh** [bobd91/magedebugbar#1]
Fatal error: Class 'MageDebugBar\MageDebugBar' not found in /var/www/mage/.modman/magedebugbar/php/app/code/community/BobD91/MageDebugBar/Model/Observer.php on line 35

**Comment by bobd91** [comment]
I can see from the .modman directory that you have not followed the installation instructions.  MageDebugBar requires the Composer class loader so if you do not have that set up correctly then it will not work.
